name: Electron Build

on:
  push:
    branches:
      - master # 或者你希望触发构建的分支名
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-latest # 使用Ubuntu最新版本作为运行环境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2' # 指定要使用的Node.js版本

      - name: Install dependencies
        run: yarn install# 或 npm ci 如果你使用npm

      - name: Build Electron app
        run: |
          yarn build
          # 或指定特定平台：yarn electron-builder build --linux --win --mac

      - name: Publish to GitHub Releases (可选)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe, dist/*.dmg, dist/*.deb, dist/*.rpm # 上传不同平台的打包结果
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的默认token发布新版本

