name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build # 替换成你的构建命令

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./dist/myGitTool Setup 1.0.0.exe
          asset_name: myGitTool.exe
          asset_content_type: application/octet-stream
          upload_url: https://api.github.com/repos/lengsukq/my-git-tool/releases/assets
