name: Electron Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build:win
      - name: Upload
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          name: dist
          path: dist
  release:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          name: dist
          path: dist
      - name: Create release
        uses: actions/create-release@v2
        with:
          tag_name: v1.0.0
          release_name: v1.0.0
          artifacts: dist/*
