name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Electron app for Windows
        run: |
          yarn build # 替换成你的构建命令

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: myGitTool.exe
          path: /dist
          content-type: application/zip
